CryptoApi/Controllers/CoinPairsController.cs
using CryptoApi.Models;
using CryptoApi.Models.DB;
using CryptoApi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CryptoApi.Controllers;
/// <summary>
///     Контроллер страниц всех пар и конкретной пары.
/// </summary>
public class CoinPairsController : Controller
{
    private readonly ILogger<HomeController> _logger;

    private CDbM db;
    private CBlocksHelperVM blocksHelper;

    /// <summary>
    ///     Конструктор. заполняет  необходимые поля при создании модели.
    /// </summary>
    public CoinPairsController(ILogger<HomeController> logger, CDbM db, CBlocksHelperVM blocks)
    {
        _logger = logger;

        this.db = db;
        this.blocksHelper = blocks;
    }

    /// <summary>
    ///     Отображает страницу всех пар.
    /// </summary>
    [Route("/crypto-pairs")]
    public IActionResult Index([FromServices] CCoinPairsVM model, int page, string filter = null)
    {
        if (filter == null)
        {
            model.Init(HttpContext);
        }
        else
        {
            if (filter == "" || filter == "#") return Redirect($"/crypto-pairs");

            model.Init(HttpContext, filter);
        }

        return View(model);
    }

    /// <summary>
    ///     Отображает страницу конкретной пары. Через get параметры принимает идентификаторы самих пар.
    /// </summary>
    [Route("/crypto-pairs/{coin1}-to-{coin2}")]
    public IActionResult Pair([FromServices] CCoinPairVM model)
    {
        ViewBag.Blocks = blocksHelper;
        model.Init(HttpContext);

        return View(model);
    }

    /// <summary>
    ///     Отображает страницу Privacy.
    /// </summary>
    public IActionResult Privacy()
    {
        return View();
    }

    /// <summary>
    ///     Отображает страницу ошибки.
    /// </summary>
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CryptoApi/Controllers/CoinsController.cs
using CryptoApi.Models;
using CryptoApi.Models.DB;
using CryptoApi.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CryptoApi.Controllers;

/// <summary>
///     Контроллер страниц всех монет и конкретной монеты.
/// </summary>
public class CoinsController : Controller
{
    private readonly ILogger<HomeController> _logger;

    private CDbM db;
    private CBlocksHelperVM blocksHelper;

    /// <summary>
    ///     Конструктор. заполняет  необходимые поля при создании модели.
    /// </summary>
    public CoinsController(ILogger<HomeController> logger, CDbM db, CBlocksHelperVM blocks)
    {
        _logger = logger;

        this.db = db;
        this.blocksHelper = blocks;
    }

    /// <summary>
    ///     Отображает страницу всех монет.
    /// </summary>
    [Route("/coins")]
    public IActionResult Index([FromServices] CCoinsVM model)
    {
        model.Init(HttpContext);

        return View(model);
    }

    /// <summary>
    ///     Отображает страницу конкретной монеты. Через get параметры принимает идентификатор самой монеты.
    /// </summary>
    [Route("/coins/{coin}")]
    public IActionResult Coin([FromServices] CCoinVM model)
    {
        ViewBag.Blocks = blocksHelper;
        model.Init(HttpContext);
        return View(model);
    }

    /// <summary>
    ///     Отображает страницу Privacy.
    /// </summary>
    public IActionResult Privacy()
    {
        return View();
    }

    /// <summary>
    ///     Отображает страницу ошибки.
    /// </summary>
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CryptoApi/Views/Shared/_AboutSmall.cshtml
@{
    //@model IEnumerable<CTextBlockVM>
}
<div class="dc-about-small">
    <h3 class="dcg-h3">About Us</h3>
    <p class="dc-about-small__content">
        We are an independent development team. Our mission is to improve the user experience in crypto world. We see great potential in blockchain technology and want to contribute to its ecosystem.
    </p>
</div>

CryptoApi/Views/Shared/_CoinPair.cshtml
@using CryptoApi.Models.DB;
@model CCoinPairDataVM

<div class="dc-coin-pair">
    <div class="dc-coin-pair__wrapper dcg-shadow-hover dcg-shadow-md">
        <div class="dc-coin-pair__head">
            <div class="dc-coin-pair__coin">
                <a asp-controller="Coins" asp-action="Coin" asp-route-coin="@Model.data.name_1" class="dc-coin-pair__coin-head">
                    <img src="@Model.coin1.image" alt="coin-image" loading="lazy">
                    <h3 class="dcg-h3">
                        @Model.data.name_1
                    </h3>
                </a>
                @if(Model.coin1.day_change < 0)
                {
                    <span class="dcg-value-down">@Model.data.day_percent_change_1%</span>
                }
                else if (Model.coin2.day_change == null)
                {
                    <span>-</span>
                }
                else 
                {
                    <span class="dcg-value-up">+@Model.data.day_percent_change_1%</span>
                }
            </div>
            <svg icon="arrow-right-darkgray" class="dcg-icon-arrow-right"></svg>
            <div class="dc-coin-pair__coin">
                <a asp-controller="Coins" asp-action="Coin" asp-route-coin="@Model.data.name_2" class="dc-coin-pair__coin-head">
                    <img src="@Model.coin2.image" alt="coin-image" loading="lazy">
                    <h3 class="dcg-h3"> 
                        @Model.data.name_2
                    </h3>
                </a>
                    
                @if(Model.coin2.day_change < 0)
                {
                    <span class="dcg-value-down">@Model.data.day_percent_change_2%</span>
                }
                else if (Model.coin2.day_change == null)
                {
                    <span>-</span>
                }
                else
                {
                    <span class="dcg-value-up">+@Model.data.day_percent_change_2%</span>
                }
            </div>
        </div>
        <span class="dc-coin-pair__value">
            1 @Model.data.name_1 = @Model.data.price_2 &nbsp; @Model.data.name_2
        </span>
        <a class="dcg-btn dcg-btn_small" asp-controller="CoinPairs" asp-action="Pair" asp-route-coin1="@Model.data.name_1" asp-route-coin2="@Model.data.name_2">
            <svg icon="exchange-cycle-light"></svg>
            <span>Exchange</span>
        </a>
    </div>
</div>

CryptoApi/Views/Shared/_CoinPairInfo.cshtml
@using CryptoApi.ViewModels
@model CCoinPairVM
<div class="dc-coin-pair-info dcg-tpg"> @*flex*@
    <div class="row">
        <div class="col">
            <table> 
                <tr>
                    <td>
                        <span>Name</span>
                    </td>
                    <td>
                        <span>@Model.pair.data.name_full_1</span>
                    </td>
                    <td>
                        <span>@Model.pair.data.name_full_2</span>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Symbol</span>
                    </td>
                    <td>
                        <span>@Model.pair.data.name_1</span>
                    </td>
                    <td>
                        <span>@Model.pair.data.name_2</span> 
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Circulating supply</span>
                    </td>
                    <td>
                        @if(Model.pair.data.circulating_supply_1 == null || Model.pair.data.circulating_supply_1 == "")
                        {
                            <span>-</span>   
                        } 
                        else
                        {
                            <span>$@Model.pair.data.circulating_supply_1</span>
                        }
                    </td>
                    <td>
                        @if(Model.pair.data.circulating_supply_2 == null || Model.pair.data.circulating_supply_2 == "")
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>$@Model.pair.data.circulating_supply_2</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Max supply</span>
                    </td>
                    <td>
                        @if(Model.pair.data.max_supply_1 == null || Model.pair.data.max_supply_1 == "")
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>$@Model.pair.data.max_supply_1</span>
                        }
                    </td>
                    <td>
                        @if(Model.pair.data.max_supply_2 == null || Model.pair.data.max_supply_2 == "")
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>$@Model.pair.data.max_supply_2</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Cmc rank</span>
                    </td>
                    <td>
                        @if(Model.pair.data.cmc_rank_1 == null)
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>@Model.pair.data.cmc_rank_1</span>
                        }
                    </td>
                    <td>
                        @if(Model.pair.data.cmc_rank_2 == null)
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>@Model.pair.data.cmc_rank_2</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Volume 24h</span>
                    </td>
                    <td>
                        @if(Model.pair.data.volume_24h_1 == null)
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>$@Model.pair.data.volume_24h_1</span>
                        }
                    </td>
                    <td>
                        @if(Model.pair.data.volume_24h_2 == null)
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span>$@Model.pair.data.volume_24h_2</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Percent change 24h</span>
                    </td>
                    <td>
                        @if(Model.pair.data.day_percent_change_1 < 0)
                        {
                            <span class="dcg-value-down">@(Model.pair.data.day_percent_change_1)%</span>
                        }
                        else if (Model.pair.coin1.day_percent_change == null)
                        {
                            <span>-</span>
                        }
                        else
                        {
                            <span class="dcg-value-up">@(Model.pair.data.day_percent_change_1)%</span>
                        }
                    </td>
                    <td>
                        @if(Model.pair.data.day_percent_change_2 < 0)
                        {
                            <span class="dcg-value-down">@(Model.pair.data.day_percent_change_2)%</span>
                        }
                        else if (Model.pair.data.day_percent_change_2 == null)
                        {
                            <span>-</span>
                        }
                        else
                        {
                            <span class="dcg-value-up">@(Model.pair.data.day_percent_change_2)%</span>
                        }
                    </td>
                </tr>
                <tr>
                    <td>
                        <span>Percent change 7d</span>
                    </td>
                    <td>
                        @if(Model.pair.data.week_percent_change_1 == null)
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span class="dcg-value-up">@(Model.pair.data.week_percent_change_1)%</span>
                        }
                    </td>
                    <td>
                        @if(Model.pair.data.week_percent_change_2 == null)
                        {
                            <span>-</span>   
                        }
                        else
                        {
                            <span class="dcg-value-up">@(Model.pair.data.week_percent_change_2)%</span>
                        }
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

CryptoApi/Views/Shared/_CoinPairs.cshtml
@model IEnumerable<CCoinPairDataVM>

<div class="dc-coin-pairs">
    <div class="dcg-section__head">
        <h2 class="dcg-h2">Popular Coin Pairs</h2>
        <a asp-controller="CoinPairs" asp-action="Index" class="dcg-btn dcg-btn_big">
            View Full Pairs List
            <svg icon="arrow-right-light" class="dcg-icon-arrow-right"></svg>
        </a>
    </div>
    <div class="row">
        @foreach(var pair in Model)
        {
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
                @await Html.PartialAsync("_CoinPair", pair)
            </div>
        }
    </div>
    <div class="dcg-section__foot">
        <a asp-controller="CoinPairs" asp-action="Index" class="dcg-btn dcg-btn_big">
            View Full Pairs List
            <svg icon="arrow-right-light" class="dcg-icon-arrow-right"></svg>
        </a>
    </div>
</div>

CryptoApi/Views/Shared/_CoinWidget.cshtml
@model (string coin1, string coin2)

<div class="dc-coin-widget">
    <div class='dc-coin-widget__wrapper'>
        @*<div id='2'></div>*@
        <script src='https://s3.tradingview.com/tv.js'></script>
        <script async>
            new TradingView.MediumWidget(
            {
                'symbols': [
                    [
                        '@(Model.coin1)@(Model.coin2)'
                    ]
                ],
                'chartOnly': false,
                'width': 684,
                'height': 272,
                'locale': 'en',
                'colorTheme': 'light',
                'gridLineColor': 'rgba(240, 243, 250, 0)',
                'fontColor': '#787B86',
                'isTransparent': false,
                'autosize': false,
                'showFloatingTooltip': true,
                'showVolume': false,
                'scalePosition': 'no',
                'scaleMode': 'Normal',
                'fontFamily': 'Trebuchet MS, sans-serif',
                'noTimeScale': false,
                'chartType': 'area',
                'lineColor': '#2962FF',
                'bottomColor': 'rgba(41, 98, 255, 0)',
                'topColor': 'rgba(41, 98, 255, 0.3)',
                'container_id': '2'
            });
        </script>
    </div>
</div>

CryptoApi/Views/Shared/_Coins.cshtml
@model IEnumerable<CCoinDataVM>

<div class="dc-coins">
    <div class="dcg-section__head">
        <h2 class="dcg-h2">Popular Crypto-Fiat Amounts</h2>
        <a asp-controller="Coins" asp-action="Index" class="dcg-btn dcg-btn_big">
            Find out more Amounts
            <svg icon="arrow-right-light" class="dcg-icon-arrow-right"></svg>
        </a>
    </div>
    <div class="dc-coins__list">
        <div class="row">
            @foreach(var coin in Model)
            {
                <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 ">
                    @await Html.PartialAsync("_Coin", coin)
                </div>
            }
        </div>
    </div>
    <div class="dcg-section__foot">
        <a asp-controller="Coins" asp-action="Index" class="dcg-btn dcg-btn_big">
            Find out more Amounts
            <svg icon="arrow-right-light" class="dcg-icon-arrow-right"></svg>
        </a>
    </div>
</div>

CryptoApi/Views/Shared/_CoinsTable.cshtml
<div class="coin-pairs-table"  style="padding-bottom: 30px">
    <div class="data-table__wrap">
        <table class="data-table">
            <thead class="data-table__header">
                <tr class="data-table__header-items">
                    <th class="data-table__header-item data-table__header-item--pair" style="width:236px;">
                        <div class="data-table__header-item-wrap data-table__header-item-wrap--left">
                            <div class="header-title">
                                Coin Name
                            </div>
                        </div>
                    </th>
                    <th class="data-table__header-item data-table__header-item--lastPrice" style="width:200px;">
                        <div class="data-table__header-item-wrap data-table__header-item-wrap--right">
                            <div class="header-title">
                                Fiat purchase
                            </div>
                        </div>
                    </th>
                    <th class="data-table__header-item data-table__header-item--pointer data-table__header-item--changePerc" style="width:120px;">
                        <div class="data-table__header-item-wrap data-table__header-item-wrap--right">
                            <div class="data-table__header-item-icon"><i
                                    class="svg-icon data-table__sort-direction"></i></div>
                            <div class="header-title">
                                Fixed rate
                            </div>
                        </div>
                    </th>
                    <th class="data-table__header-item data-table__header-item--high24h" style="width:156px;">
                        <div class="data-table__header-item-wrap data-table__header-item-wrap--right">
                            <div class="header-title">
                                Available for exchange
                            </div>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody class="data-table__body">
                @for (int i = 0; i < 20; i++)
                {
                    @await Html.PartialAsync("_CoinsTableLine")
                }
            </tbody>
        </table>
    </div>
</div>

CryptoApi/Views/Shared/_HeadAdvantages.cshtml
<div class="dc-head-advantages">
    <ul class="dc-head-advantages__list">
        <li class="d-inline-block">
            <div class="dc-head-advantages__advantage">
                <div class="dc-head-advantages__done d-inline-block">
                    <svg icon="done-small"></svg>
                </div>
                <div class="dcg-head-advantage d-inline-block">
                    <span class="d-block dc-head-advantages__text">301+</span>
                    <span class="d-block dc-head-advantages__text-light">supported coins</span>
                </div>
            </div>
        </li>
        <li class="d-inline-block">
            <div class="dc-head-advantages__advantage">
                <div class="dc-head-advantages__done d-inline-block">
                    <svg icon="done-small"></svg>
                </div>
                <div class="dc-head-advantages__advantage d-inline-block">
                    <span class="d-block dc-head-advantages__text">Exchange</span>
                    <span class="d-block dc-head-advantages__text-light">without limits</span>
                </div>
            </div>
        </li>
        <li class="d-inline-block">
            <div class="dc-head-advantages__advantage">
                <div class="dc-head-advantages__done d-inline-block">
                    <svg icon="done-small"></svg>
                </div>
                <div class="dc-head-advantages__advantage d-inline-block">
                    <span class="d-block dc-head-advantages__text">Non-custodial</span>
                    <span class="d-block dc-head-advantages__text-light">security</span>
                </div>
            </div>
        </li>
    </ul>
</div>

CryptoApi/Views/Shared/_Logo.cshtml
<div class="dc-logo">
    <a asp-controller="Home" asp-action="Index">
        <img src="/images/logo.svg" alt="logo" loading="lazy" />
    </a>
</div>

CryptoApi/Views/Shared/_NewsList.cshtml
@{
    IEnumerable<string> tags1 = new List<string>() { "btg", "predictions" };
    IEnumerable<string> tags2 = new List<string>() { "vet", "predictions" };
    IEnumerable<string> tags3 = new List<string>() { "meta", "predictions" };

}
<div class="dc-news-list">
    <div class="dcg-section__head">
        <h2 class="dcg-h2">Latest News</h2>
        <a href="#" class="dcg-btn dcg-btn_big">
            View All
            <svg icon="arrow-right-light" class="dcg-icon-arrow-right"></svg>
        </a>
    </div>
    <div class="row">
            <div class="col-lg-4 col-md-6">
                @await Html.PartialAsync("_NewsSketch", ("/pictures/bitcoin-gold.jpg" , tags1, "Bitcoin Gold (BTG) Price Prediction for 2022 - 2030", "Atomex provides websocket API for wallets and market makers. Contact us if you have questions regarding integration.", "April 7", "#"))
            </div>
            <div class="col-lg-4 col-md-6">
                @await Html.PartialAsync("_NewsSketch", ("/pictures/metaverse-tokens.jpg" , tags2, "How and Where to Buy VeChain (VET) to Buy VeChain Fast and Safely in 2022?", "Atomex provides websocket API for wallets and market makers. Contact us if you have...", "March 13", "#"))
            </div>
            <div class="col-lg-4 col-md-6">
                @await Html.PartialAsync("_NewsSketch", ("/pictures/where-to-buy-vechain.jpg" , tags3, "Are Metaverse Tokens a Good Investment Option?", "Atomex provides websocket API for wallets and market makers. Contact us if you have questions regarding integration.", "March 1", "#"))
            </div>
    </div>
    <div class="dcg-section__foot">
        <a href="#" class="dcg-btn dcg-btn_big">
            View All
            <svg icon="arrow-right-light" class="dcg-icon-arrow-right"></svg>
        </a>
    </div>
</div>

CryptoApi/Views/Shared/_PageHeadMain.cshtml
<div class="dc-page-head-main">
    
</div>

CryptoApi/Views/Shared/_PageHeadPairs.cshtml
<div class="dc-page-head-pairs">
    page-head-pairs
</div>

CryptoApi/Views/Shared/_SubheaderCoinPair.cshtml
@model (CTextBlockVM pagehead, (string coin1_name, string coin2_name) coins)

<div class="dc-subheader-coin-pair">
    <div class="row">
        <div class="col">
            @await Html.PartialAsync("_Breadcrumbs", new[] { ("Cryptocurrency Exchange Pairs", Url.RouteUrl(new { Action = "Index", Controller = "CoinPairs" })), (Model.coins.coin1_name + " to " + Model.coins.coin2_name, "") })
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1 class="dcg-h1">@Html.Raw(Model.pagehead.title)</h1>
            @await Html.PartialAsync("_CoinWidget", (Model.coins.coin1_name, "usd"))
        </div>
        <div class="col">
            @await Html.PartialAsync("_ExchangeWidget", (Model.coins.coin1_name.ToLower(), Model.coins.coin2_name.ToLower()))
        </div>
    </div>
</div>

CryptoApi/Views/Shared/_TextBlocks.cshtml
@model IEnumerable<CTextBlockVM>

@foreach(var block in Model)
{
    @await Html.PartialAsync("_TextBlock", block)
}